CREATE TABLE fraudTrain (
    column1          INT,               
    trans_date_trans_time DATETIME,     
    cc_num           BIGINT,            
    merchant         NVARCHAR(255),     
    category         NVARCHAR(255), 
    amt              DECIMAL(10,2),     
    first_name       NVARCHAR(100),     
    last_name        NVARCHAR(100),     
    gender           CHAR(1),           
    street           NVARCHAR(255),     
    city             NVARCHAR(100),     
    state            CHAR(2),           
    zip              CHAR(5),           
    lat              DECIMAL(9,6),      
    long             DECIMAL(9,6),     
    city_pop         INT,               
    job              NVARCHAR(255),    
    dob              DATE,              
    trans_num        VARCHAR(50),       
    unix_time        BIGINT,            
    merch_lat        DECIMAL(9,6),      
    merch_long       DECIMAL(9,6),     
    is_fraud         TINYINT            
);
